### PR TITLE
Refactorización de código

### PR DESCRIPTION
**Pull request by jpavonabian**
Modificado requirements.txt. No dejaba hacer pip install -r requirements.txt por un error en una versión de un módulo.
Convertido translator.py a una clase python.
Ajustado el código para llamar a esa clase.

### CODE REVIEW

**Comment by metalalchemist** [comment]
hola!  el código se rompe al intentar invocar a LANGUAGES. supongo que hay que importar a LANGUAGES del translator?
por otro lado, onnxruntime1.14.1 si existe.  no será que por la 1.15.1 se te cuelga el windows? yo lo estoy probando en win10  con el 1.15.1 y se abrió normal. pero es lo que se me ocurrió.
mira,  te confirmo.


Collecting onnxruntime==1.14.1
  Downloading onnxruntime-1.14.1-cp310-cp310-win_amd64.whl (6.5 MB)
     ---------------------------------------- 6.5/6.5 MB 6.6 MB/s eta 0:00:00
Requirement already satisfied: coloredlogs in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (
from onnxruntime==1.14.1) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (
from onnxruntime==1.14.1) (23.5.26)
Requirement already satisfied: numpy>=1.21.6 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages
 (from onnxruntime==1.14.1) (1.23.5)
Requirement already satisfied: packaging in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (fr
om onnxruntime==1.14.1) (23.1)
Requirement already satisfied: protobuf in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (fro
m onnxruntime==1.14.1) (4.21.12)
Requirement already satisfied: sympy in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (from o
nnxruntime==1.14.1) (1.12)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-pac
kages (from coloredlogs->onnxruntime==1.14.1) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages
(from sympy->onnxruntime==1.14.1) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (
from humanfriendly>=9.1->coloredlogs->onnxruntime==1.14.1) (3.4.1)
Installing collected packages: onnxruntime
Successfully installed onnxruntime-1.14.1

**Comment by jpavonabian** [comment]
Ciertamente, perdona.

Subo un commit, que se me fue la cabeza y no subí el último, mil disculpas.

Con onnxruntime1.14.1 consigo el siguiente error:

Requirement already satisfied: numpy in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 9)) (1.25.2)                                                                                 

ERROR: Could not find a version that satisfies the requirement onnxruntime==1.14.1 (from versions: 1.15.0, 1.15.1)      

ERROR: No matching distribution found for onnxruntime==1.14.1                                                           

Un saludo.

 

De: cesar verastegui ***@***.***> 
Enviado el: lunes, 4 de septiembre de 2023 3:30
Para: metalalchemist/VeTube ***@***.***>
CC: Jesús Pavón Abián ***@***.***>; Author ***@***.***>
Asunto: Re: [metalalchemist/VeTube] Refactorización de código (PR #11)

 

hola! el código se rompe al intentar invocar a LANGUAGES. supongo que hay que importar a LANGUAGES del translator?
por otro lado, onnxruntime1.14.1 si existe. no será que por la 1.15.1 se te cuelga el windows? yo lo estoy probando en win10 con el 1.15.1 y se abrió normal. pero es lo que se me ocurrió.
mira, te confirmo.

Collecting onnxruntime==1.14.1
Downloading onnxruntime-1.14.1-cp310-cp310-win_amd64.whl (6.5 MB)
---------------------------------------- 6.5/6.5 MB 6.6 MB/s eta 0:00:00
Requirement already satisfied: coloredlogs in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (
from onnxruntime==1.14.1) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (
from onnxruntime==1.14.1) (23.5.26)
Requirement already satisfied: numpy>=1.21.6 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages
(from onnxruntime==1.14.1) (1.23.5)
Requirement already satisfied: packaging in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (fr
om onnxruntime==1.14.1) (23.1)
Requirement already satisfied: protobuf in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (fro
m onnxruntime==1.14.1) (4.21.12)
Requirement already satisfied: sympy in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (from o
nnxruntime==1.14.1) (1.12)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-pac
kages (from coloredlogs->onnxruntime==1.14.1) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages
(from sympy->onnxruntime==1.14.1) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\cesit\appdata\local\programs\python\python310\lib\site-packages (
from humanfriendly>=9.1->coloredlogs->onnxruntime==1.14.1) (3.4.1)
Installing collected packages: onnxruntime
Successfully installed onnxruntime-1.14.1

**Comment by rmcpantoja** [comment]
Efectivamente, no hay una versión de Python 3.11 para onnxruntime 1.14.1. Aun así, la versión actual (1.15) debería correr sin problemas. El paquete se utiliza para controlar los modelos de piper TTS.

**Comment by jpavonabian** [comment]
En efecto, funciona sin problemas. Y si no especificas versión, como hice yo, también lo hace.

 

 

De: Mateo Cedillo ***@***.***> 
Enviado el: lunes, 4 de septiembre de 2023 14:35
Para: metalalchemist/VeTube ***@***.***>
CC: Jesús Pavón Abián ***@***.***>; Author ***@***.***>
Asunto: Re: [metalalchemist/VeTube] Refactorización de código (PR #11)

 

Efectivamente, no hay una versión de Python 3.11 para onnxruntime 1.14.1. Aun así, la versión actual (1.15) debería correr sin problemas. El paquete se utiliza para controlar los modelos de piper TTS.

**Comment by metalalchemist** [comment]
sigo recibiendo el mismo error. mira la ruta que tomo es entrar a vetube luego mas opciones luego abrir configuración.


Traceback (most recent call last):
  File "D:\descargas\VeTube-traductor\VeTube.py", line 369, in appConfiguracion
    self.cf=ajustes.configuracionDialog(self)
  File "D:\descargas\VeTube-traductor\ajustes.py", line 34, in __init__
    for k in translator.LANGUAGES: idiomas_disponibles.append(translator.LANGUAGES[k])
  File "D:\descargas\VeTube-traductor\translator.py", line 12, in LANGUAGES
    return LANGUAGES
NameError: name 'LANGUAGES' is not defined

**Comment by jpavonabian** [comment]
Arreglado, ahora sí.

 

En efecto, se me había pasado el importar el LANGUAGES.

 

Ha sido abrir translator.py y darme cuenta.

 

Acabo de probarlo y ya no se rompe.

 

De: cesar verastegui ***@***.***> 
Enviado el: martes, 5 de septiembre de 2023 2:26
Para: metalalchemist/VeTube ***@***.***>
CC: Jesús Pavón Abián ***@***.***>; Author ***@***.***>
Asunto: Re: [metalalchemist/VeTube] Refactorización de código (PR #11)

 

sigo recibiendo el mismo error. mira la ruta que tomo es entrar a vetube luego mas opciones luego abrir configuración.

Traceback (most recent call last):
File "D:\descargas\VeTube-traductor\VeTube.py", line 369, in appConfiguracion
self.cf=ajustes.configuracionDialog(self)
File "D:\descargas\VeTube-traductor\ajustes.py", line 34, in init
for k in translator.LANGUAGES: idiomas_disponibles.append(translator.LANGUAGES[k])
File "D:\descargas\VeTube-traductor\translator.py", line 12, in LANGUAGES
return LANGUAGES
NameError: name 'LANGUAGES' is not defined

**Comment by metalalchemist** [comment]
muchas gracias, lo pruebo y te  cuento.   por cierto, dejaremos entonces onxruntime asi como lo tienes tu.

**Comment by jpavonabian** [comment]
Puede dejarse y mirarlo con detalle en otra pr isue o lo que sea.

**Pull request merged**
